FROM alpine:3.20

WORKDIR /app

# Install only essential packages for CP compilation
RUN apk add --no-cache g++ gcc libc-dev libstdc++

# Copy your executor script
COPY run.sh /app/run.sh
RUN chmod +x /app/run.sh

# Entrypoint
ENTRYPOINT ["/app/run.sh"]
